### PR TITLE
Sorting all software compromises from the table

### PR DESCRIPTION
**Pull request by mgobbi289**
All table entries were sorted based on their `report_date` (with some minor fixes).

### CODE REVIEW

**Comment by jspeed-meyers** [comment]
@mgobbi289, thank you for this too! We'll merge after reviewing. WE REALLY APPRECIATE THIS!

Out of curiosity, are your using this dataset for research? If so, we'd love to see what you publish and please let us know if there are ways to make the dataset more useful for your efforts.

**Comment by jspeed-meyers** [comment]
@bentztozer, if this looks good to you, pleas merge.

**Comment by mgobbi289** [comment]
Yes, I found this dataset very useful to start my research, so I wanted to contribute a little by adding what I found on my part. It is a recent project about malicious code in open source repositories.

I added some additional features to the entries I researched, such as the language used, the impact and behavior of the malware, and other useful references about each attack. Perhaps this information could be useful for future researchers.

**Comment by jspeed-meyers** [comment]
Well, thanks again! When you publish, let us know and we're glad to link to your published research.

**Pull request merged**
